// Code generated by FormatModule tool. DO NOT EDIT.
package jpg

import (
	"FormatModules/generator" // Dynamically include each required import path

	"fmt" // Dynamically include each required import path

	"github.com/knetic/govaluate" // Dynamically include each required import path

	"io" // Dynamically include each required import path
)

// DQTPayload represents the DQTPayload structure.
type DQTPayload struct {
	QuantizationData []byte `` // Raw data containing precision/index and table values

}

// Read populates the struct fields by reading from an io.Reader, using optional context.
// The context can be used by dynamic length calculations.
func (s *DQTPayload) Read(r io.Reader, ctx interface{}) error {
	var err error // Declare err only if needed for Read

	// <-- Declare tmpUint8 once if needed

	// Read QuantizationData ([]byte)

	// ... (string, []byte, other numeric types logic remains the same) ...

	// Dynamic length []byte field: QuantizationData using expression: ctx.SegmentLength - 2
	expressionStr := `ctx.SegmentLength - 2`
	expression, errExpr := govaluate.NewEvaluableExpressionWithFunctions(expressionStr, generator.GetExpressionFunctions()) // Use helpers
	if errExpr != nil {
		return fmt.Errorf("parsing length expression for QuantizationData ('%s'): %w", expressionStr, errExpr)
	}
	parameters := map[string]interface{}{"s": s, "ctx": ctx}
	evalResult, errEval := expression.Evaluate(parameters)
	if errEval != nil {
		return fmt.Errorf("evaluating length expression for QuantizationData ('%s'): %w", expressionStr, errEval)
	}
	var size int
	switch v := evalResult.(type) { // Type conversion logic
	case float64:
		size = int(v)
	case float32:
		size = int(v)
	case int:
		size = v
	case int64:
		size = int(v)
	case int32:
		size = int(v)
	case uint:
		size = int(v)
	case uint64:
		size = int(v)
	case uint32:
		size = int(v)
	case uint16:
		size = int(v)
	case uint8:
		size = int(v)
	default:
		return fmt.Errorf("length expression for QuantizationData ('%s') evaluated to non-numeric type %T", expressionStr, evalResult)
	}
	if size < 0 {
		return fmt.Errorf("length expression for QuantizationData ('%s') evaluated to negative size %d", expressionStr, size)
	}
	s.QuantizationData = make([]byte, size)
	_, err = io.ReadFull(r, s.QuantizationData)
	if err != nil {
		return fmt.Errorf("reading QuantizationData ([]byte[dynamic length %s]): %w", expressionStr, err)
	}

	return nil // If we got here, all reads using 'err' were successful

}

// Write serializes the struct fields into an io.Writer.
func (s *DQTPayload) Write(w io.Writer) error {
	var err error // Declare err only if needed for Write
	// NOTE: tmpUint8 is not needed for Write method as we write directly from s.FieldName

	// Write QuantizationData ([]byte)

	// ... (string, []byte, other numeric types logic remains the same) ...

	_, err = w.Write(s.QuantizationData)
	if err != nil {
		return fmt.Errorf("writing QuantizationData ([]byte): %w", err)
	}

	return nil // If we got here, all writes using 'err' were successful

}
