// Code generated by FormatModule tool. DO NOT EDIT.
package jpg

import (
	"FormatModules/generator" // Dynamically include each required import path

	"encoding/binary" // Dynamically include each required import path

	"fmt" // Dynamically include each required import path

	"github.com/knetic/govaluate" // Dynamically include each required import path

	"io" // Dynamically include each required import path
)

// SOSPayload represents the SOSPayload structure.
type SOSPayload struct {
	Ns uint8 `` // Number of image components in scan

	ScanHeader []byte `` // Component selectors (Csj, Tdj/Taj), Spectral selection (Ss, Se), Approx. bits (Ah, Al)

}

// Read populates the struct fields by reading from an io.Reader, using optional context.
// The context can be used by dynamic length calculations.
func (s *SOSPayload) Read(r io.Reader, ctx interface{}) error {
	var err error // Declare err only if needed for Read

	var tmpUint8 uint8 // <-- Declare tmpUint8 once if needed

	// Read Ns (uint8)

	// ... (string, []byte, other numeric types logic remains the same) ...
	// Handle uint8
	// Use assignment '=' instead of 'var'
	err = binary.Read(r, binary.LittleEndian, &tmpUint8) // <-- Assign to existing tmpUint8
	if err != nil {
		return fmt.Errorf("reading Ns (uint8): %w", err)
	}
	s.Ns = tmpUint8
	// ... (other types like uint16, uint32 etc.) ...

	// Read ScanHeader ([]byte)

	// ... (string, []byte, other numeric types logic remains the same) ...

	// Dynamic length []byte field: ScanHeader using expression: s.Ns * 2 + 4
	expressionStr := `s.Ns * 2 + 4`
	expression, errExpr := govaluate.NewEvaluableExpressionWithFunctions(expressionStr, generator.GetExpressionFunctions()) // Use helpers
	if errExpr != nil {
		return fmt.Errorf("parsing length expression for ScanHeader ('%s'): %w", expressionStr, errExpr)
	}
	parameters := map[string]interface{}{"s": s, "ctx": ctx}
	evalResult, errEval := expression.Evaluate(parameters)
	if errEval != nil {
		return fmt.Errorf("evaluating length expression for ScanHeader ('%s'): %w", expressionStr, errEval)
	}
	var size int
	switch v := evalResult.(type) { // Type conversion logic
	case float64:
		size = int(v)
	case float32:
		size = int(v)
	case int:
		size = v
	case int64:
		size = int(v)
	case int32:
		size = int(v)
	case uint:
		size = int(v)
	case uint64:
		size = int(v)
	case uint32:
		size = int(v)
	case uint16:
		size = int(v)
	case uint8:
		size = int(v)
	default:
		return fmt.Errorf("length expression for ScanHeader ('%s') evaluated to non-numeric type %T", expressionStr, evalResult)
	}
	if size < 0 {
		return fmt.Errorf("length expression for ScanHeader ('%s') evaluated to negative size %d", expressionStr, size)
	}
	s.ScanHeader = make([]byte, size)
	_, err = io.ReadFull(r, s.ScanHeader)
	if err != nil {
		return fmt.Errorf("reading ScanHeader ([]byte[dynamic length %s]): %w", expressionStr, err)
	}

	return nil // If we got here, all reads using 'err' were successful

}

// Write serializes the struct fields into an io.Writer.
func (s *SOSPayload) Write(w io.Writer) error {
	var err error // Declare err only if needed for Write
	// NOTE: tmpUint8 is not needed for Write method as we write directly from s.FieldName

	// Write Ns (uint8)

	// ... (string, []byte, other numeric types logic remains the same) ...
	// Handle numeric types
	err = binary.Write(w, binary.LittleEndian, s.Ns) // Write directly
	if err != nil {
		return fmt.Errorf("writing Ns (uint8): %w", err)
	}
	// ... (other types like uint16, uint32 etc.) ...

	// Write ScanHeader ([]byte)

	// ... (string, []byte, other numeric types logic remains the same) ...

	_, err = w.Write(s.ScanHeader)
	if err != nil {
		return fmt.Errorf("writing ScanHeader ([]byte): %w", err)
	}

	return nil // If we got here, all writes using 'err' were successful

}
