// Code generated by FormatModule tool. DO NOT EDIT.
package bmp

import (
	"fmt"
	"io"
	
)

// ImageData represents the ImageData structure.
type ImageData struct {
    
    PixelData []byte // RGB pixel data
    
}

// Read populates the struct fields by reading from an io.Reader.
func (s *ImageData) Read(r io.Reader) error {
	 // Declare err only if needed for Read
	

    
	// Read PixelData ([]byte)
	
		
	// This field cannot be read automatically.
	return fmt.Errorf("cannot automatically read []byte field PixelData without a defined length") // Returns early
		
	
    

	
	
	
}

// Write serializes the struct fields into an io.Writer.
func (s *ImageData) Write(w io.Writer) error {
	var err error // Declare err only if needed for Write

    
	// Write PixelData ([]byte)
	
	_, err = w.Write(s.PixelData) // Uses err
	if err != nil {
		return fmt.Errorf("writing PixelData ([]byte): %w", err)
	}
	
    

	
	
	return nil
	
}
